import"./assets/styles-e61fb95b.js";const d=[{id:3,img:"https://static.dnipro-m.ua/cache/products/1335/catalog_origin_325102.jpg",name:"Шліфмашина",price:1299,description:"Кутова шліфувальна машина Dnipro-M GS-98 – модель, яка поєднує в собі оптимальне співвідношення потужності, ваги та мобільності. Конструкція шліфмашини сприяє зручній та надійній роботі, навіть однією рукою. Низький рівень шуму та вібрації, двопозиційне розташування додаткової рукоятки під кутом 100 градусів, мінімізує втому під час шліфування."},{id:4,img:"https://static.dnipro-m.ua/cache/products/8284/catalog_origin_322127.jpg",name:"Пила",price:11049,description:"Мобільна акумуляторна ланцюгова пила DCS-200BC DUAL призначена для обрізання зайвих гілок, спилювання дерев та чагарника, заготівлі дров, покрою будматеріалів та демонтажних робіт. Її просто використовувати у будь-яких місцях: на висоті, на виїзних роботах, у лісі або саду. При цьому Вам не потрібно буде турбуватися про підключення до мережі."},{id:5,img:"https://static.dnipro-m.ua/cache/products/2024/catalog_origin_323413.jpg",name:"Рівень",price:897,description:"Рівень серії ProVision виробництва DNIPRO-M має не тільки високу точність вимірювань і чудові захисні властивості, а й надає максимальний комфорт користувачеві в процесі експлуатації."},{id:6,img:"https://static.dnipro-m.ua/cache/products/6566/catalog_origin_316315.jpg",name:"Тример",price:3699,description:"Тример електричний Dnipro-M 110 призначений для покосу густої трави, а також кущів з діаметром стовбура до 10 мм."},{id:7,img:"https://static.dnipro-m.ua/cache/products/6483/catalog_origin_325859.jpg",name:"Мотокоса",price:11049,description:"Мотокоса Dnipro-M 43 призначена для покосу трави, чагарників, бур'янів, газонів, а також для заготівлі сіна в невеликих масштабах.    Використовується для польових робіт на садовій ділянці площею до 2000 м2."},{id:8,img:"https://static.dnipro-m.ua/cache/products/2745/catalog_origin_319770.jpg",name:"Генератор",price:10890,description:"Бензиновий генератор GX-25 номінальною потужністю 2,5 кВт забезпечить автономність побутових приладів на дачі або у приватному будинку. Ви зможете одночасно підключити до нього освітлення, холодильник, зарядку телефону, ноутбук та водяний насос."}],s="clientBasket",e=document.querySelector(".js-product-list");e.insertAdjacentHTML("afterbegin",p(d));e.addEventListener("click",n);function n(r){if(!r.target.classList.contains("js-add-product-btn"))return;const t=JSON.parse(localStorage.getItem(s))??[],o=Number(r.target.closest(".js-product-card").dataset.productId),c=d.find(({id:i})=>i===o),a=t.findIndex(({id:i})=>i===o);a===-1?(c.qnt=1,t.push(c)):t[a].qnt+=1,localStorage.setItem(s,JSON.stringify(t))}function p(r){return r.map(({description:t,price:o,name:c,img:a,id:i})=>`
     <li class="product-card js-product-card" data-product-id=${i}>
          <img class="product-img" src="${a}" alt="${c}" />
          <h2 class="product-title">${c}</h2>
          <p class="product-description">${t}</p>
          <p class="product-price">Priсe ${o} грн</p>
          <button class="product-add-btn js-add-product-btn" type="button">Add to basket</button>
      </li>`).join("")}
//# sourceMappingURL=commonHelpers2.js.map
